name = "TensorCrossInterpolation"
uuid = "b261b2ec-6378-4871-b32e-9173bb050604"
authors = ["Ritter.Marc <Ritter.Marc@physik.uni-muenchen.de>, Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.7.1"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"

[compat]
EllipsisNotation = "1"
julia = "1.6"
QuanticsGrids = "0.1.1"

[extras]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Random", "ITensors", "Zygote", "Optim", "QuanticsGrids"]
