name = "TensorCrossInterpolation"
uuid = "b261b2ec-6378-4871-b32e-9173bb050604"
authors = ["Ritter.Marc <Ritter.Marc@physik.uni-muenchen.de> and contributors"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[extensions]
TCIITensorConversion = ["ITensors"]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[targets]
test = ["Test", "Random", "ITensors", "Zygote", "Optim"]
